### ISSUE TITLE
[QUESTION]: Readme tutorial

### ISSUE THREAD

**Issue by MillyKookie** [XeroxDev/DSharpPlus.ModalCommands#5]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.

### Question

Hi,

On the readme, what is `_sp` at `Services = _sp` ?
I don't see any variable initialized with this name or type in the example.

**Comment by XeroxDev** [comment]
Hey!

`_sp` indicates `ServiceProvider` for DI (Dependency Injection).

Hope this helped!

**Comment by XeroxDev** [comment]
Due to inactivity, I guess this helped you?

I'm gonna /close this issue for now, if you've still questions or issues, feel free to reopen it or to create a new ticket.
